env:
  browser: true
  es6: true
  jquery: true
  jest: true
extends:
  ["eslint:recommended",
   "google",
   "plugin:flowtype/recommended",
   "plugin:react/recommended"]
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: "[iI]gnored"
  flowtype/no-types-missing-file-annotation:
    - 0
  no-console: ["error", { allow: ["warn", "error"] }]
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
  ecmaFeatures:
      jsx: true
settings:
  react:
    version: "16.6.0"
parser: "babel-eslint"
plugins: ["flowtype"]
